### ISSUE TITLE
Parsing Project Configurations

### ISSUE THREAD

**Issue by SDRausty** [BuildAPKs/buildAPKs#1]
BuildAPKs could parse project configuration files to integrate libraries:

1.  Some of the configuration files are:
   * `app/build.gradle`
   * `build.gradle`
   * `gradle/wrapper/gradle-wrapper.properties`
   * `proguard-project.txt`
   * `proguard.cfg`
   * `project.properties`

What other configuration files desire parsing?

2. How should libraries be handled by BuildAPKs:
  * Should libraries be downloaded, symlinked and linked into the project that is being compiled?
  * Should the libraries be downloaded, cached and unpacked into the source code?  This method may be more transparent while working with the project sourcecode.

3. How should the build scripts integrate the tasks of parsing, downloading and linking these libraries into each individual project?  Device space is important while working with multiple projects.

**Comment by SDRausty** [comment]
> Warning: A script that uses a library does not run as quickly as it would if all the code were contained within a single script project. Although libraries can make development and maintenance more convenient, you should use them sparingly in projects where speed is critical. Because of this issue, library use should be limited in add-ons.

Reference https://developers.google.com/apps-script/guides/libraries

**Comment by SDRausty** [comment]
>  A script that uses a library does not run as quickly as it would if all the code were contained within a single script project. Although libraries can make development and maintenance more convenient, you should use them sparingly in projects where speed is critical. Because of this issue, library use should be limited in add-ons.

Reference https://developers.google.com/apps-script/guides/libraries

**Comment by SDRausty** [comment]
Some frequent errors are:
```
number of errors / type of error
4813 error: Error: No resource found that matches the given name: attr 'colorPrimary'.
4800 error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
4773 error: Error: No resource found that matches the given name: attr 'colorAccent'.
4518 error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.
575 error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.NoActionBar'.
```
```

**Comment by HemanthJabalpuri** [comment]
@SDRausty
Can you please refer some of the below links so that we can may add support for aidl, libraries support and extra.

https://github.com/t-arn/java-ide-droid/blob/master/0_build-prod.bat
https://github.com/t-arn/java-ide-droid/blob/master/build.bsh
https://github.com/pdaxrom/cctools/blob/master/cctools-repo/misc/sdktools/aproject

**Comment by SDRausty** [comment]
@HemanthJabalpuri thank you for sharing these links.  I wanted to parse them, so I used the raw portal, i.e. https://raw.githubusercontent.com/t-arn/java-ide-droid/master/0_build-prod.bat

Since adding artifacts and libraries is one of a few ways to resolve building source code that depends on libraries and artifacts.  This issue https://github.com/BuildAPKs/buildAPKs/issues/2 is open to resolve parsing project configuration files.

**Comment by SDRausty** [comment]
In comment https://github.com/BuildAPKs/buildAPKs/issues/1#issuecomment-534638948_ the number of errors are condensed by type of error.  What is the minumun required to resolve errors 1, 2 and 3?

**Comment by HemanthJabalpuri** [comment]
> In comment [#1 (comment)](https://github.com/BuildAPKs/buildAPKs/issues/1#issuecomment-534638948)_ the number of errors are condensed by type of error. What is the minumun required to resolve errors 1, 2 and 3?

@SDRausty 
I will tell you the detailed steps for this in a week as a new repo of me.
Above errors are because of appcmpat library is missing.

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
See this https://github.com/HemanthJabalpuri/AndroidExplorer.

**Comment by SDRausty** [comment]
This https://github.com/BuildAPKs/buildAPKs/issues/3 issue is created for resolving parsing using the android.jar file.

**Comment by SDRausty** [comment]
@HemanthJabalpuri please reffer to https://github.com/BuildAPKs/buildAPKs.developers.tools in reffence to:

> See this https://github.com/HemanthJabalpuri/AndroidExplorer.

**Comment by SDRausty** [comment]
@HemanthJabalpuri modifying `android.jar` might better than adding libraries. Hence https://github.com/BuildAPKs/buildAPKs/issues/3 is created...

**Comment by SDRausty** [comment]
> add support for

As adding support for can be resolved in many ways, the following topics are created in seeking routes toward untegration:

   * https://github.com/BuildAPKs/buildAPKs/issues/2 Adding Artifacts
   * https://github.com/BuildAPKs/buildAPKs/issues/3 Modifying `android.jar`

**Comment by SDRausty** [comment]
> add support for

Adding support for can be resolved in many ways, the following topics are created in seeking routes toward integration:

   * https://github.com/BuildAPKs/buildAPKs/issues/2 Adding Artifacts
   * https://github.com/BuildAPKs/buildAPKs/issues/3 Modifying `android.jar`

**Comment by SDRausty** [comment]
This https://github.com/BuildAPKs/buildAPKs/commit/aa2fde90fb79c37a8c101bd1d7fc7b086bdaf68e commit, and accompanying commits in [shlibs.sh](https://github.com/shlibs/shlibs.bash/commits/master) and [shlibs.bash](https://github.com/shlibs/shlibs.sh/commits/master) create `B*NAMES` files in ~/buildAPKs/var/db with this workset: 
  * login 
  * download size 
  * build time
  *  number of AndroidManifest.xml files found 
  * number of APKs built

**Comment by SDRausty** [comment]
This repository https://github.com/BuildAPKs/db.BuildAPKs is created to assit in parsing repository files.  This https://github.com/BuildAPKs/db.BuildAPKs/blob/master/BNAMES file holds statistics:  GitHub login, repository projects download size, build time, AndroidManifest.xml files found and built APKs found for each login that successfully built on device.

**Comment by SDRausty** [comment]
@HemanthJabalpuri any thoughts regarding:

> detailed steps 
> Above errors are because of appcmpat library is missing.

> Loading artifacts and libraries into the compilation:  Adding 0 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/var/cache/lib into build main:  Adding 545 artifacts and libraries from directory /system into build main: DONE

![Screenshot_20191213-212441](https://user-images.githubusercontent.com/27742457/70842256-61989400-1def-11ea-8588-f0c7915de1e3.png)

**Comment by SDRausty** [comment]
```
Beginning build in /data/data/com.termux/files/home/buildAPKs/sources/github/users/hemanthjabalpuri/HemanthJabalpuri-AndroidExplorer-3bf49e5                                                                                                                                                    
Loading artifacts and libraries into the compilation:  Adding 3 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/var/cache/lib into build HemanthJabalpuri-AndroidExplorer-3bf49e5:  Adding 9 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/sources/github/users/hemanthjabalpuri/HemanthJabalpuri-AndroidExplorer-3bf49e5/libs into build HemanthJabalpuri-AndroidExplorer-3bf49e5:  Adding 553 artifacts and libraries from directory /system into build HemanthJabalpuri-AndroidExplorer-3bf49e5: DONE
```
```
Loading artifacts and libraries into the compilation:  Adding 3 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/var/cache/lib into build main:  Adding 547 artifacts and libraries from directory /system into build main: DONE
```

```
[22:09lib]$ pwd                               
/data/data/com.termux/files/home/buildAPKs/var/cache/lib                                        
[22:09lib]$ ls                                                                                  
appcompat-1.0.2.aar  emoji-appcompat-1.0.0.aar  test-services-1.0.0.apk                         
[22:09lib]$ grep -ir "Theme.AppCompat.Light.DarkActionBar" *r
[22:09lib]$ grep -ir "Theme.AppCompat.Light.DarkActionBar" *k
Binary file test-services-1.0.0.apk matches
```

```
res/values/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.DarkActionBar'.
res/values/styles.xml:9: error: Error: No resource found that matches the given name: attr 'colorAccent'.
res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorPrimary'.                                                                                                                                                                                      
res/values/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.                                                                                                                                          
res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.                                                                                                                                                                                       res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.                                                                                                                                                                                      res/values/styles.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
```

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
I don't know what's going wrong in your script.
I know only basic shell scripting.

You can build `Android-Explorer` app with `build_old.sh` and `build_new.sh` scripts from the repo.

Those are very basic scripts.

**Comment by SDRausty** [comment]
@HemanthJabalpuri the https://github.com/HemanthJabalpuri/AndroidExplorer/tree/master/libs directory is present, and:
`Loading artifacts and libraries into the compilation:  Adding 3 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/var/cache/lib into build HemanthJabalpuri-AndroidExplorer-3bf49e5:  Adding 9 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/sources/github/users/hemanthjabalpuri/HemanthJabalpuri-AndroidExplorer-3bf49e5/libs into build HemanthJabalpuri-AndroidExplorer-3bf49e5:  Adding 959 artifacts and libraries from directory /system into build HemanthJabalpuri-AndroidExplorer-3bf49e5: DONE`

but the error persists

`res/values/styles.xml:7: error: Error retrieving parent for item: No resource found that matches the given name '@style/Theme.AppCompat.Light.DarkActionBar'.`

and the resources are present

`grep -ir "Theme.AppCompat.Light.DarkActionBar" HemanthJabalpuri-AndroidExplorer-3bf49e5/
                                                                               HemanthJabalpuri-AndroidExplorer-3bf49e5/libs/res-appcompat/values/values.xml:    <style name="Base.Theme.AppCompat.Light.DarkActionBar" parent="Base.Theme.AppCompat.Light">                   HemanthJabalpuri-AndroidExplorer-3bf49e5/libs/res-appcompat/values/values.xml:    <style name="Theme.AppCompat.Light.DarkActionBar" parent="Base.Theme.AppCompat.Light.DarkActionBar"/>         HemanthJabalpuri-AndroidExplorer-3bf49e5/res/values/styles.xml:    <style name="AppBaseTheme" parent="@style/Theme.AppCompat.Light.DarkActionBar">`

So I am not sure what [aapt package](https://github.com/BuildAPKs/buildAPKs/blob/master/scripts/bash/build/build.one.bash#L139) wants to know to compile.

> I know only basic shell scripting.

I am impressed by your work @HemanthJabalpuri and I will continue to study ` grep -ir aapt HemanthJabalpuri-AndroidExplorer-3bf49e5/ ` in the hope of successfully compiling your projects on device.

> You can build Android-Explorer app with ` build_old.sh ` and ` build_new.sh ` scripts from the repo.

On device?  How?  I've tried in Termux and Termux PRoot.

**Comment by SDRausty** [comment]
@HemanthJabalpuri adding the following line to aapt enables compilation of 
```
--auto-add-overlay -S libs/res-appcompat -S libs/res-cardview -S libs/res-design -S libs/res-recyclerview \
```

**Comment by SDRausty** [comment]
> adding the following line to aapt package enables compilation of https://github.com/HemanthJabalpuri/AndroidExplorer:
>
> ` --auto-add-overlay -S libs/res-appcompat -S libs/res-cardview -S libs/res-design -S libs/res-recyclerview \`

This is now automated with this https://github.com/BuildAPKs/buildAPKs/commit/d2f4cfd3fbed501b1c2f2befa60eb805202017e3 commit, and this https://github.com/BuildAPKs/buildAPKs/commit/536b0376319fe7664ade8a8f849921083ff04bd8 commit.

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
may be
`--extra-packages android.support.v7.appcompat:android.support.v7.cardview:android.support.design:android.support.v7.recyclerview` is missing in your script.

**Comment by SDRausty** [comment]
Commit https://github.com/BuildAPKs/buildAPKs/commit/92ba219cb88be8687a6214a8db77d09b2ce66c0c in particular https://github.com/BuildAPKs/buildAPKs/blob/92ba219cb88be8687a6214a8db77d09b2ce66c0c/var/db/BNAMES expands this issue.

> This https://github.com/BuildAPKs/db.BuildAPKs repository is created to assit in parsing repository files. File [var/db/BNAMES](https://github.com/BuildAPKs/db.BuildAPKs/blob/master/BNAMES) holds statistics: GitHub login, build time, repository projects *.tar.gz download size, AndroidManifest.xml files found and built APKs found for each login that successfully built APK on device.

**Comment by SDRausty** [comment]
Commit https://github.com/BuildAPKs/buildAPKs/commit/718f4dfdef4dd959b1c96ce050ceb63697bb3327 restores PRoot compatability.
