### ISSUE TITLE
Parsing Gradle Files for Dependencies

### ISSUE THREAD

**Issue by JanuszChmiel** [BuildAPKs/buildAPKs#13]
I AM aware, that it will not be easy. But unfortunately, more and more projects are Gradle based. And more and more project are bing used by Android studio, which uses specific folder structures of The project and in some cases, it is even not simply possible to build those Gradle based projects outside Android studio by only typing gradlew AssembleDebug or by typing similar command.
Yours approach is really revolutionar. Why? .dex files of Java source sample apps are very small. There is not app compat .jar library build as default and if projects allow this, The apps are really very small and memory efficient.
So.
How complex would be to compile Open JDK from source directly on Android devices. Or do you think, that even Gradle based projects would be compiled to apk with no need to use Open JDK or Android build tools?
You have collected many functioning Examples. It is Java code and I have tested apps and really, it work without issue.
So really, excellent project.

What do you thinkk about finding The algorithm for building even complex Gradle based projects?
Sure. Users who are using compatible kernel and non case insensitive file system can even install some Debian based distribution by using Proot and it is even possible to experiment with Android SDK for Linux by this way.
But yours project is more effective. It is not based on Proot so no next machine code retranslation. Faster execution of building of apks.
I Am ready to test and debug on this complex idea with you. Thanks to The opportunity to run Termux by using SSH protocol, I can debug and work by using Putty and NVDA screen reader. So even I do not see at all, I can constructively help.

Sure, I can not reformat my EXT4 partitions inside my phone so The file system of my device will stop to be file name case insensitive.
It is not possible without rooting and it would end with totally corrupted phone.
But I can debug by using Termux.
Yours project have even The potential to allow not only visually impaired Pascal developers to develop Pascal apps directly on Android device.
The potential is very big.

**Comment by SDRausty** [comment]
@JanuszChmiel gradle is available in [TermuxArch](https://github.com/TermuxArch) on handheld.   To install gradle in Arch Linux you can use: ` pc gradle ` after using [ ` setupTermuxArch.bash ` ](https://github.com/TermuxArch/TermuxArch/blob/master/setupTermuxArch.bash).

![Screenshot_20191208-124924](https://user-images.githubusercontent.com/27742457/70393551-35c57a80-19b9-11ea-85da-584035914fab.png)
 ```
BUILD SUCCESSFUL in 17s
1 actionable task: 1 executed
```

Parsing gradle files for dependencies can be added to [BuildAPKs.](https://github.com/BuildAPKs)  [FLIST](https://github.com/shlibs/shlibs.bash/blob/master/buildAPKs/prep.bash#L48) has names of some of the configuration files used to build APKs.  How would you integrate these configuration files into the build process?   Submit pull requests  [here ](https://github.com/shlibs/shlibs.bash/pulls) and [here](https://github.com/shlibs/shlibs.sh/pulls) regarding this issue.

**Comment by JanuszChmiel** [comment]
Oh I Am so deeply sad, that creators of my phone model have formateed EXT4 file system as case file insensitive file system. So I can not use yours perfect ArchLinux script.
It would be really amazing to build Gradle projects directly on Android evice with no need to buy expensive and complex to operate apps on Play store.

**Comment by SDRausty** [comment]
> it will not be easy

Downloading dependencies like "appcompat" from [https://mvnrepository.com/artifact/androidx.appcompat/appcompat](https://mvnrepository.com/artifact/androidx.appcompat/appcompat) into ` ~/buildAPKs/var/cache/lib ` is possible.  Commit https://github.com/BuildAPKs/buildAPKs/commit/3d51ec2d5a06b9eba310c7b4824db463aad4b735 automates loading artifacts from the ` ~/buildAPKs/var/cache/lib ` directory.  This should ease processing dependencies.

**Comment by SDRausty** [comment]
> it will not be easy

Downloading dependencies like [appcompat](https://mvnrepository.com/artifact/androidx.appcompat/appcompat) from [https://mvnrepository.com](https://mvnrepository.com/) into ` ~/buildAPKs/var/cache/lib ` is possible. 

Commit https://github.com/BuildAPKs/buildAPKs/commit/3d51ec2d5a06b9eba310c7b4824db463aad4b735 automates loading artifacts from the ` ~/buildAPKs/var/cache/lib ` directory.  This should ease processing dependencies.

**Comment by SDRausty** [comment]
> ready to test and debug on this complex idea with you

@JanuszChmiel ` for NAME in $(awk '{print $1}' ~/buildAPKs/var/db/BNAMES) ; do ~/buildAPKs/scripts/bash/build/build.github.bash $NAME ; done ` is one of a few starting points.

**Comment by SDRausty** [comment]
Here are a couple of links that can assist in resolving this issue:
* https://dl.google.com/android/studio/maven-google-com/stable/offline-gmaven-stable.zip 2724MB
* https://gradle.org/releases/
* https://mvnrepository.com/artifact/androidx.appcompat/appcompat

**Comment by SDRausty** [comment]
@JanuszChmiel are you familiar with https://help.github.com/en/github/managing-packages-with-github-packages/configuring-gradle-for-use-with-github-packages?

**Comment by Vixeliz** [comment]
Termux has gradle packged now btw not sure if this can be used to our advantage

**Comment by SDRausty** [comment]
>[UserLAnd app](https://play.google.com/store/apps/details?id=tech.ula&hl=en&gl=US)'s Ubuntu OS supports more packages (like `openjdk-8-jdk`) than Termux.

    pkg list-available | grep jdk
    openjdk-17/stable,now 17.0-15 aarch64 [installed,automatic]

How do compare in your opinion?

**Comment by SDRausty** [comment]
>So I will start with Termux followed by ArchlInux for Termux from mR Rausty to find The current status.

Please tell us about your progress.  If ouput is lengthy, please PR in https://github.com/BuildAPKs/docsBuildAPKs/tree/master/incoming here.

**Comment by SDRausty** [comment]
>How would you download these files using curl from mvnrepository.com?

I have just written a short script which took many hours to write that partly automates the  quest of [Adding Artifacts #2](https://github.com/BuildAPKs/buildAPKs/issues/2):
```
#!/usr/bin/env sh
# Example usage 'mclookup.sh androidx.appcompat appcompat 1.3.1'
# Attributed from  https://github.com/rbi13/env/blob/master/java.al
set -eu

_MCLOOKUP_(){
 if [ -z ${3:-} ]; then
    SEARCH=$1
    termux-open "https://mvnrepository.com/search?q=${SEARCH}"
  else
    GROUPID=$1
    ARTIFACTID=$2
    [ -n "$3" ] && VERSION=$3 || VERSION='latest'
termux-open "https://mvnrepository.com/artifact/${GROUPID}/${ARTIFACTID}/${VERSION}"
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.aar
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.jar
  fi
}

_MCLOOKUP_ $@
# mclookup.sh EOF
```

This should help with:
>download the aars

and jars too.

_Originally posted by @SDRausty in https://github.com/BuildAPKs/buildAPKs/issues/24#issuecomment-934466551_

Duplicate post at [Reddit](https://www.reddit.com/r/termux/comments/q1xlk2/i_have_just_written_a_short_script_which_took/).

**Comment by SDRausty** [comment]
>[UserLAnd app](https://play.google.com/store/apps/details?id=tech.ula&hl=en&gl=US)'s Ubuntu OS supports more packages (like `openjdk-8-jdk`) than Termux.

    pkg list-available | grep jdk
    openjdk-17/stable,now 17.0-15 aarch64 [installed,automatic]

How do these compare in your opinion?

**Comment by JanuszChmiel** [comment]
I have been stuck because I can not download Build tools. No matter which version number would I use.
For example.
If I type in Termux outside Proot Linux distro The following command.

./sdkmanager --sdk_root=/data/data/com.termux/files/home/android --install "build-tools;19.1.0"
I AM getting The following error
~/android/bin $ ./sdkmanager --sdk_root=/data/data/com.termux/files/home/android --install "build-tools;19.1.0"
Warning: Dependant package with key emulator not found!
Warning: Unable to compute a complete list of dependencies.
~/android/bin $                         ] 10% Computing updates...
~/android/bin $

Sure, I have also tried The latest version of Build tools with The same error. Termux is complex to build from Termux, because it is necessary to use Android NDK version ndkVersion=22.1.7171670. And unfortunately, even though it is possible to download this bundle, powerful Google engineers did not released NDK for AARCH64 architecture. Sure. It would be possible to install Archlinux with Qemu, but unfortunately, Qemu do not work for now with Termux latest stable repo. So this informatic rebus is out of my scope to solve.

**Comment by SDRausty** [comment]
I tried to build the build tools many months ago using `yay` with [TermuxArch](https://termuxarch.github.io/TermuxArch/).  The builds were successfull, but using them on arm architecture was not a success.  Also, I had found a link at https://github.com/search to the build tools for arm architecture source code.  I tried finding the git repo again to test them a few of days ago without success.

We were successfull in creating `orcaconf`; @JanuszChmiel can you please share the commands, all of them up to this point?
>I have been stuck because I can not download Build tools.

**Comment by SDRausty** [comment]
>Warning: Dependant package with key emulator not found!

I get the same error.  I have also tried `adb`:
`error: no devices/emulators found` the errors might be related.
