### ISSUE TITLE
How to build just one project?

### ISSUE THREAD

**Issue by konijn** [BuildAPKs/buildAPKs#17]
Greetings,

love the potential of this. I've decided to work on one project and would like to be able to just build that one project instead of all the projects. What is the easiest way to do that? Besides deleting all the other projects of course ;)

**Comment by konijn** [comment]
What I've done is copy buildAPKs/scripts/sh/build/build.sh to the one project I want to compile. The only thing missing was the copy from local build to shared storage. Also the generated file will no longer have a timestamp in the name.

**Comment by SDRausty** [comment]
Hi,

> love the potential of this. 

Thank you. I find your comment humbling. Musing on this topic has given results:

> I've decided to work on one project and would like to be able to just build that one project instead of all the projects. 

Command [`~/buildAPKs/build.repo.bash`](https://github.com/BuildAPKs/buildAPKs.github/blob/master/build.repo.bash) was recently added. It enables building just one repository. This command has been tested with [https://github.com/search](https://github.com/search/) and [https://gitlab.com/explore](https://gitlab.com/explore) successfully.

> What is the easiest way to do that? 

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find repo candidates for inclusion in this project @konijn, please share addresses to the sourcecode here in ttopic.

> Besides deleting all the other projects of course ;)

Directory [`~/buildAPKs/var/cache/tarballs/`](https://github.com/BuildAPKs/buildAPKs.tarballs) is being designed to assist in topics of device space and working APK sourcecode restoration.

**Comment by SDRausty** [comment]
Command [`build.repo.bash`](https://github.com/BuildAPKs/buildAPKs.github/blob/master/build.repo.bash) should compile only one git repository from source that is hosted on GitHub and GitLab.
