### ISSUE TITLE
Unable to choose a specific repository to build

### ISSUE THREAD

**Issue by sobaee** [BuildAPKs/buildAPKs#18]
Hello
I tried to use this comment to build this apk from this github account but it failed:
~/buildAPKs/build.github.bash https://github.com/tytydraco/LADB/

But with the following comment (without specifing a single apk repository) :
~/buildAPKs/build.github.bash https://github.com/tytydraco/
it worked well but it tried to build every single apk developed by "tytydraco" user (and he has a lot!)!!

I only need to build "LADB" repository directly without needing to wait for all apk repositories of the user to be built.

Could you help please?

**Comment by SDRausty** [comment]
> repository directly without needing to wait for all apk repositories 

@sobaee please see [How to build just one project? #17](https://github.com/BuildAPKs/buildAPKs/issues/17) for more information.

**Comment by SDRausty** [comment]
Issue [Building 1 new APK #21](https://github.com/SDRausty/buildAPKs/issues/21) should have useful information too.

**Comment by Tisckkytt** [comment]
@sobaee Have you managed to build LADB after all?

**Comment by sobaee** [comment]
@Tisckkytt 
No, of course no
It failed to build with both ways

**Comment by SDRausty** [comment]
> repository directly without needing to wait for all apk repositories of the user to be built.

Command ~/buildAPKs/build.repo.bash was just added. It enables building just one repository. This command has been tested with https://github.com/search and https://gitlab.com/explore/ successfully.

> Could you help please?

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find repo candidates for inclusion, please share an address to the sourcecode here in this topic.

**Comment by SDRausty** [comment]
> > repository directly without needing to wait for all apk repositories of the user to be built.
> 
> Command ~/buildAPKs/build.repo.bash was just added. It enables building just one repository. This command has been tested with https://github.com/search and https://gitlab.com/explore/ successfully.
> 
> > Could you help please?
> 
> EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment
> 
> If you find repo candidates for inclusion, please share an address to the sourcecode here in this topic.
