### ISSUE TITLE
How to build local apk

### ISSUE THREAD

**Issue by Children-Next-Door** [BuildAPKs/buildAPKs#19]
Hello！

I want to build my own local APK instead of the APK that comes with the warehouse.

What do I need to do？

**Comment by SDRausty** [comment]
Hi!

> I want to build my own local APK instead of the APK that comes with the warehouse.

1 Edit the code in any of the projects: `~/buildAPKs/sources`
2 buildAPKs.tutorials has tutorial APK projects.

**Comment by SDRausty** [comment]
> build my own local APK

This command:
`~/buildAPKs/scripts/bash/build/build.in.dir.bash` should be useful for you too.

**Comment by SDRausty** [comment]
> I want to build my own local APK instead of the APK that comes with the warehouse.

Command ~/buildAPKs/build.repo.bash was just added. It enables building just one repository. This command has been tested with https://github.com/search and https://gitlab.com/explore/ successfully.

> What do I need to do？

EXAMPLE USAGE: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

If you find repo candidates for inclusion, please share an adress to the sourcecode here in this topic.
