### ISSUE TITLE
Pregunta 

### ISSUE THREAD

**Issue by Yisus7u7** [BuildAPKs/buildAPKs#20]
Hola, estoy enrredado con todo esto, este projecto construlle solo los apks que trae en los scripts, o puedo construir un apk que hice en mi celular?, si se pueden compilar apks locales como lo hago?

**Comment by SDRausty** [comment]
Hola,
> o puedo construir un apk que hice en mi celular?
> si se pueden compilar apks locales como lo hago?

Use el comando `~/buildAPKs/scripts/bash/build/build.in.dir.bash` después de la clonación.

Alternativamente, puede probar este comando `~/buildAPKs/build.repo.bash` que se acaba de agregar hoy. Permite construir un solo repositorio. Este comando ha sido probado con https://github.com/search y https://gitlab.com/explore con éxito.

EJEMPLO DE USO: build.repo.bash https://github.com/BuildAPKs/buildAPKs.entertainment

Si encuentra candidatos de repositorio para su inclusión, comparta la dirección del código fuente aquí en este tema.

**Comment by Yisus7u7** [comment]
Okey, y los apks deben ser echos específicamente en java?, osea hago una carpeta con todo el contenido del apk?

**Comment by SDRausty** [comment]
> específicamente en java?

Compatible con Java y nativo. 
> hago una carpeta con todo el contenido del apk?

El comando `~/buildAPKs/build.repo.bash` creará una carpeta con todo el contenido del apk mediante la clonación y la construcción.
