### ISSUE TITLE
copy.apk.bash file not found

### ISSUE THREAD

**Issue by cubetronic** [BuildAPKs/buildAPKs#21]
```
~/.../src/main $ ~/buildAPKs/scripts/bash/build/build.one.bash
/data/data/com.termux/files/home/buildAPKs/scripts/bash/build/build.one.bash: line 65: /data/data/com.termux/files/home/buildAPKs/scripts/bash/shlibs/buildAPKs/copy.apk.bash: No such file or directory
/data/data/com.termux/files/home/buildAPKs/scripts/bash/build/build.one.bash: line 21: JID: unbound variable
```

and i still don't really know what this means: "simply run build.one.bash in the directory of the program you wish to make by calling it by name". i have never gotten any of this to work.

**Comment by cubetronic** [comment]
i ran `/data/data/com.termux/files/home/buildAPKs/scripts/bash/build/buildSamples.bash` and it built around 200 apk's. i didn't know where they were at first but i found them in `/data/data/com.termux/files/home/buildAPKs/var/cache/builtAPKs/samples4.20210605`.

so at least i know it works somehow. i'm interested in building Vanilla Music Player, which uses gradle and so i guess will take more work but.. i'm just trying to figure out how all this works.

i think the documentation could be cleaned up. there seem to be pages that are nearly identical but different in key places.. and some of the paths seem to be outdated in the docs

**Comment by cubetronic** [comment]
i'm starting to see how there are a lot of different repositories, many with outdated info, and they are cross-linking to each other. i think it would be good to clean things up.

so here is what i understand is going on:

- there are two github accounts: BuildAPKs and SDRausty.
- each have a BuildAPKs repository. the one under BuildAPKs is current. The one under SDRausty is behind.
- The README.md at BuildAPKs/BuildAPKs links to buildapks.github.io
- The instructions at buildapks.github.io are outdated: The site has 5 pages which are all very, very similar, all with instructions to clone `https://github.com/sdrausty/buildAPKs` which is old. Also, four of those pages have instructions to run `./buildAPKs/scripts/build/buildMyFirstAPKs.sh' which appears to be very outdated because it is not a valid path or file on either repository.

**Comment by SDRausty** [comment]
Thanks for taking an intrest in this project.

> - there are two github accounts: BuildAPKs and SDRausty.
