### ISSUE TITLE
insufficient documentation

### ISSUE THREAD

**Issue by cubetronic** [BuildAPKs/buildAPKs#23]
regarding building any and all apks, SDRausty said:

> With build.github.bash you can build nearly an unlimited number of APKs which are available at GitHub

source of quote: https://www.reddit.com/r/termux/comments/itrm0b/comment/gc127fg

but how? where is the documentation? i want to fork, modify, and build https://github.com/vanilla-music/vanilla which requires gradle.

**Comment by cubetronic** [comment]
to be clear, vanilla music player requires the following:

```
java jdk 1.8u251+ (<1.9)   installed in TermuxArch
gradle 6.5+                not in archlinuxarm
sdkmanager (to get tools)  not in archlinuxarm
platform-tools             not in archlinuxarm
build-tools;29.0.2         not in archlinuxarm
platforms;android-29       not in archlinuxarm
```
so far all i have is java:
```
[user10:14~]$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-b10)
OpenJDK 64-Bit Zero VM (build 25.292-b10, interpreted mode)
[user10:14~]$
```

**Comment by SDRausty** [comment]
> where is the documentation?

You're welcome to create a PR here: https://github.com/BuildAPKs/docsBuildAPKs/pulls

> requires gradle.

Hopefully, one day Gradle builds will be automated. Artifacts can be used; please see https://github.com/BuildAPKs/buildAPKs/blob/master/scripts/bash/build/build.one.bash#L80&&#L122 for more information about using libraries.

> With build.github.bash you can build nearly an unlimited number of APKs which are available at GitHub

File [opt/db/BNAMES](https://raw.githubusercontent.com/BuildAPKs/db.BuildAPKs/master/BNAMES) contains built APKs information.
