### ISSUE TITLE
Confused exactly what this is

### ISSUE THREAD

**Issue by Vixeliz** [BuildAPKs/buildAPKs#24]
I understand this can be used to build android apps on termux. I have a few questions. Firstly is it possible to add my own applications to build? Secondly would it be possible to build [this](https://github.com/love2d/love-android)? After the first build do you have to be connected to the internet to build an application? Sorry for the questions just not sure exactly what this project is and if it has a use besides the included apk build scripts.

**Comment by SDRausty** [comment]
>I understand this can be used to build android apps on termux.

Yes, you can.  Thousands of apps can be built at present.

>I have a few questions. Firstly is it possible to add my own applications to build? Secondly would it be possible to build this?

Yes, this is possible with this command:
`build.repo.bash https://github.com/love2d/love-android`

This project can still be greatly improved;  Please consider creating a pull request;  Here is the result of `build.repo.bash https://github.com/love2d/love-android`:
![Screenshot_20211001-102659](https://user-images.githubusercontent.com/27742457/135638996-1f9747c9-ee73-42a4-83e0-a47907264918.png)

>After the first build do you have to be connected to the internet to build an application?

No, an Internet connection is not required after the first build;  Please enjoy 🎵 🎶

**Comment by Vixeliz** [comment]
Hmmm it seems that love does not build with this there are many errors. Is there any way to get a log to upload?

**Comment by Vixeliz** [comment]
Also thx you for this amazing project and the response!

**Comment by SDRausty** [comment]
>love does not build

`love` should install with the command:
`pc love`
```
==> Running TermuxArch command pc love v2.0.1246...
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mesa will be installed before its libglvnd dependency

Packages (40) alsa-lib-1.2.5.1-3  alsa-topology-conf-1.2.5.1-1
              alsa-ucm-conf-1.2.5.1-1  desktop-file-utils-0.26-1
              hidapi-0.10.1-1  libdrm-2.4.107-1  libglvnd-1.3.4-1
              libibus-1.5.25-3  libmodplug-0.8.9.0-3  libogg-1.3.5-1
              libomxil-bellagio-0.9.3-3  libpciaccess-0.16-2  libtheora-1.1.1-5
              libunwind-1.5.0-1  libusb-1.0.24-2  libvorbis-1.3.7-2
              libx11-1.7.2-1  libxau-1.0.9-3  libxcb-1.14-1  libxcursor-1.2.0-2
              libxdamage-1.1.5-3  libxdmcp-1.1.3-3  libxext-1.3.4-3
              libxfixes-6.0.0-1  libxrender-0.9.10-4  libxshmfence-1.3-2
              libxxf86vm-1.1.4-4  llvm-libs-12.0.1-4
              lm_sensors-1:3.6.0.r41.g31d1f125-1
              luajit-git-v2.1.0.beta3.r201.gdd5032ed-1  mesa-21.2.2-1
              mpg123-1.29.0-1  openal-1.21.1-1  sdl2-2.0.16-2
              shared-mime-info-2.0+57+gc1d1c70-1  vulkan-icd-loader-1.2.191-1
              wayland-1.19.0-1  xcb-proto-1.14.1-3  xorgproto-2021.5-1
              love-11.3-1

Total Download Size:    54.27 MiB
Total Installed Size:  303.36 MiB

:: Proceed with installation? [Y/n]
```

>thx you for this amazing project and the response!

You are very welcome; I am amazed at how this project has developed over time.  This would not be possible without contributors like you;  Thank you!

**Comment by SDRausty** [comment]
>love does not build

Or is this `build.repo.bash https://github.com/qiushi123/love` the one?

**Comment by Vixeliz** [comment]
Hello! Thx for the response again. Indeed love2d the first repo I put is the one I was wondering about. I am aware I could run via termuxarch but I would love to be able to build the apk for native use on android. Is the build failing due to the application using c/c++ code or it using gradle? Any help would be deeply appreciated

**Comment by SDRausty** [comment]
>be able to build the apk for native use on android.

What is the link to the APK source code?

**Comment by Vixeliz** [comment]
Https://github.com/love2d/love-android is for building it I believe. It doesn't actually build correctly

**Comment by Vixeliz** [comment]
Hello not trying to push at all i was just wondering if you had figured out why it wasn't building yet?

**Comment by SDRausty** [comment]
>you had figured out why it wasn't building

It wants dependancies;  This link has https://github.com/SDRausty/buildAPKs/issues?q=is%3Aissue+library more information about using libraries with BuildAPKs.  Also please see files `.conf/README.md` and `.conf/LIBAUTH` about this topic too.

**Comment by SDRausty** [comment]
>I would love to be able to build the apk for native use on android.

Ditto,  Let us see if we can make it happen!

**Comment by Vixeliz** [comment]
Ok if I understand correctly I need to go through the gradle file and find any dependencies? Also does it matter if love uses native c/c++ code?

**Comment by SDRausty** [comment]
>I would love to be able to build the apk for native use on android.

Ditto,  Let us see if we can make this happen with love too!  We have successfully integrated libraries into projects before:
a) `cat ~/buildAPKs/.conf/README.md ~/buildAPKs/.conf/LIBAUTH`
b) https://github.com/BuildAPKs/buildAPKs/issues?q=is%3Aissue+library
c) https://github.com/SDRausty/buildAPKs/issues?q=is%3Aissue+library

**Comment by SDRausty** [comment]
>Ok if I understand correctly I need to go through the gradle file and find any dependencies? 

No, start with integrating appcompat:
```
tail -4 ~/buildAPKs/var/lfhvar.txt
https://mvnrepository.com/artifact/com.android.support/appcompat-v7
https://mvnrepository.com/artifact/androidx.appcompat

# lfhvar.txt EOF
```

**Comment by Vixeliz** [comment]
Ok I have done that and added androidx.multidex as it is in the app's build.gradle file however it doesn't appear to be any different

**Comment by Vixeliz** [comment]
After changing .conf/LIBAUTH to true and adding those lines no apks show up in the build folder which Ig could be a good sign?

**Comment by Vixeliz** [comment]
It appears no artifacts are being loaded despite being in /var/cache/lib. I have made sure LIBDIRPATH is set I believe

**Comment by SDRausty** [comment]
>Also does it matter if love uses native c/c++ code?

Yes, love uses native code.  You can enable native code into the APKs by running `build.native.bash` which should change 1 to 0 in file `~/buildAPKs/.conf/DOSO` for you:
```
dx: done;  Making com.google.oboe.sample.1633385837.apk...
Searching for 'CMakeLists.txt' files in ~/buildAPKs/sources/github.com/love2d/love-android/love/src/jni/oboe/samples/parselib/src/main/; Please be patient...
Found 1 'CMakeLists.txt' file.
Processing ~/buildAPKs/sources/github.com/love2d/love-android/love/src/jni/oboe/samples/parselib/src/main/cpp/CMakeLists.txt.
Beginning cmake and make in ~/buildAPKs/sources/github.com/love2d/love-android/love/src/jni/oboe/samples/parselib/src/main/output/lib/armeabi-v7a:
-- The C compiler identification is Clang 11.1.0
-- The CXX compiler identification is Clang 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /data/data/com.termux/files/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /data/data/com.termux/files/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /data/data/com.termux/files/home/buildAPKs/sources/github.com/love2d/love-android/love/src/jni/oboe/samples/parselib/src/main/output/lib/armeabi-v7a
Scanning dependencies of target parselib
[ 11%] Building CXX object CMakeFiles/parselib.dir/stream/FileInputStream.cpp.o
[ 22%] Building CXX object CMakeFiles/parselib.dir/stream/InputStream.cpp.o
[ 33%] Building CXX object CMakeFiles/parselib.dir/stream/MemInputStream.cpp.o
[ 44%] Building CXX object CMakeFiles/parselib.dir/wav/AudioEncoding.cpp.o
[ 55%] Building CXX object CMakeFiles/parselib.dir/wav/WavChunkHeader.cpp.o
[ 66%] Building CXX object CMakeFiles/parselib.dir/wav/WavFmtChunkHeader.cpp.o
[ 77%] Building CXX object CMakeFiles/parselib.dir/wav/WavRIFFChunkHeader.cpp.o
[ 88%] Building CXX object CMakeFiles/parselib.dir/wav/WavStreamReader.cpp.o
[100%] Linking CXX static library libparselib.a
[100%] Built target parselib
Finished cmake and make in ~/buildAPKs/sources/github.com/love2d/love-android/love/src/jni/oboe/samples/parselib/src/main/output/lib/armeabi-v7a/.
No 'Android.mk' files were found: Continuing...
No 'jni' directory found: Continuing...
Adding classes.dex  to com.google.oboe.sample.1633385837.apk...
 'classes.dex'...
Signing com.google.oboe.sample.1633385837.apk: DONE
```

**Comment by Vixeliz** [comment]
Ok yes I have done that still no luck though. As said no artifacts being loaded ;-;

**Comment by Vixeliz** [comment]
It says this
```
aapt: done;  dalvikvm: begun...
Signal generated dalvikvm build.one.bash build.one.bash: EXITING...
buildAPKs signal 220 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/native2/bitmap-plasma/app/src/main by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.native2.log` file.

Running: VAR="$(grep -C 2 -ie error -ie errors "/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.native2.log")" && VAR="$(grep -v \-\- <<< $VAR)" && head <<< $VAR && tail <<< $VAR
```

**Comment by Vixeliz** [comment]
Ok I fixed that issue I think

**Comment by Vixeliz** [comment]
Still not building quite right though

**Comment by Vixeliz** [comment]
It appears it needs android.annotation and org.libsdl

**Comment by SDRausty** [comment]
>It appears it needs android.annotation and org.libsdl

These want to be added as well.

**Comment by Vixeliz** [comment]
So do I add them to the file in /var/lfhvar.txt

**Comment by SDRausty** [comment]
>Ok I have done that and added androidx.multidex as it is in the app's build.gradle file however it doesn't appear to be any different
>It appears it needs android.annotation and org.libsdl

How would you download these files using `curl` from mvnrepository.com?

>So do I add them to the file in /var/lfhvar.txt

The jars should be placed here:
```
~ $ tree ~/buildAPKs/var/cache/lib
/data/data/com.termux/files/home/buildAPKs/var/cache/lib
├── res-appcompat
├── res-cardview
├── res-design
└── res-recyclerview

4 directories, 0 files
~ $ grep LIBDIR ~/buildAPKs/bin/build.one.bash
        LIBDIRPATH=("$JDR/lib" "$JDR/libraries" "$JDR/library" "$JDR/libs" "$RDR/var/cache/lib") # modify array LIBDIRPATH to suit the projects artifact needs.
        for LIBDIR in ${LIBDIRPATH[@]} # every element in array LIBDIRPATH
                if [[ -d "$LIBDIR" ]] # library directory exists
                        DIRLIS="$(find -L "$LIBDIR" -type f -name "*.jar" 2>/dev/null)" || _PRINTSGE_ DIRLIS
                        printf "\\e[1;34m%s" "Adding $NUMIA artifacts and libraries from directory $LIBDIR into build ${PWD##*/} : "
```
This reference might also aid our work here:
https://github.com/BuildAPKs/buildAPKs/issues/1

**Comment by Vixeliz** [comment]
I'm really confused here where exactly do i download the aars to?

**Comment by Vixeliz** [comment]
Sorry for being annoying I really appreciate the help

**Comment by SDRausty** [comment]
>where exactly do i download the aars to?

They should go here `~/buildAPKs/var/cache/lib`;  However,  you have asked a very good question;  Please see this https://github.com/termux/termux-packages/issues/7279 issue for the most recent information.

**Comment by Vixeliz** [comment]
Ah I see. Does that mean I should find jars instead of Aars? Sorry if I am misunderstanding

**Comment by SDRausty** [comment]
Does that mean I should find jars instead of Aars?

>[You need to at least extract it. You can't use aar directly in classpath. That's entirely different format specific to Android OS. It is closer to APK file than JAR.](https://github.com/BuildAPKs/buildAPKs/issues/24)

**Comment by Vixeliz** [comment]
I see, curious if u have managed to get it built?

**Comment by SDRausty** [comment]
>curious if u have managed to get it built

No, I just heard about https://github.com/love2d/love-android from you;  Thank you.  Opening an issue at https://github.com/love2d/love-android/issues might be very beneficial.

**Comment by SDRausty** [comment]
>added androidx.multidex as it is in the app's build.gradle file

    $ find -name build.gradle | xargs grep api | grep -v Tr | grep -v love
    ./app/build.gradle:    api 'androidx.multidex:multidex:2.0.1'
    ./app/build.gradle:    api 'androidx.appcompat:appcompat:1.2.0'

>It appears it needs android.annotation and org.libsdl

Yes, it does:

    grep -h -r ^import | sort | uniq | grep -e android.annotation -e org.libsdl
    import android.annotation.TargetApi;                                          
    import org.libsdl.app.SDLActivity;

**Comment by SDRausty** [comment]
>How would you download these files using curl from mvnrepository.com?

I have just written a short script which took many hours to write that partly automates the  quest of [adding artifacts](https://github.com/BuildAPKs/buildAPKs/issues/2):
```
#!/usr/bin/env sh
# Example usage 'mclookup.sh androidx.appcompat appcompat 1.3.1'
# Attributed from  https://github.com/rbi13/env/blob/master/java.al
set -eu

_MCLOOKUP_(){
 if [ -z ${3:-} ]; then
  echo $2
    SEARCH=$1
    termux-open "https://mvnrepository.com/search?q=${SEARCH}"
  else
    GROUPID=$1
    ARTIFACTID=$2
    [ -n "$3" ] && VERSION=$3 || VERSION='latest'
termux-open "https://mvnrepository.com/artifact/${GROUPID}/${ARTIFACTID}/${VERSION}"
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.aar
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.jar
  fi
}

_MCLOOKUP_ $@
# mclookup.sh EOF
```

This should help with:
>download the aars

and jars too.

**Comment by SDRausty** [comment]
>to go through the gradle file and find any dependencies

    $ find -name build.gradle | xargs grep api | grep -v Tr | grep -v love
    ./app/build.gradle:    api 'androidx.multidex:multidex:2.0.1'
    ./app/build.gradle:    api 'androidx.appcompat:appcompat:1.2.0'

>It appears it needs android.annotation and org.libsdl

Yes, it does:

    grep -h -r ^import | sort | uniq | grep -e android.annotation -e org.libsdl
    import android.annotation.TargetApi;                                          
    import org.libsdl.app.SDLActivity;

This note should assit with [Parsing Project Configuration Files #1](https://github.com/BuildAPKs/buildAPKs/issues/1)

**Comment by SDRausty** [comment]
>How would you download these files using curl from mvnrepository.com?

I have just written a short script which took many hours to write that partly automates the  quest of [Adding Artifacts #2](https://github.com/BuildAPKs/buildAPKs/issues/2):
```
#!/usr/bin/env sh
# Example usage 'mclookup.sh androidx.appcompat appcompat 1.3.1'
# Attributed from  https://github.com/rbi13/env/blob/master/java.al
set -eu

_MCLOOKUP_(){
 if [ -z ${3:-} ]; then
  echo $2
    SEARCH=$1
    termux-open "https://mvnrepository.com/search?q=${SEARCH}"
  else
    GROUPID=$1
    ARTIFACTID=$2
    [ -n "$3" ] && VERSION=$3 || VERSION='latest'
termux-open "https://mvnrepository.com/artifact/${GROUPID}/${ARTIFACTID}/${VERSION}"
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.aar
curl -OL https://maven.google.com/${GROUPID%%\.*}/${ARTIFACTID}/${ARTIFACTID}/${VERSION}/${ARTIFACTID}-${VERSION}.jar
  fi
}

_MCLOOKUP_ $@
# mclookup.sh EOF
```

This should help with:
>download the aars

and jars too.

**Comment by SDRausty** [comment]
>Confused exactly what this is #24

I just announced our quest here https://www.reddit.com/r/termux/comments/q1xlk2/i_have_just_written_a_short_script_which_took/

**Comment by Vixeliz** [comment]
Awesome! Thanks for the hard work I hope we can get this building.

**Comment by Vixeliz** [comment]
BTW the script helps a ton for getting artifacts so thank you for that! Still trying to get it built though

**Comment by SDRausty** [comment]
You are welcome; Thank you for helping too.

>to /var/cache/lib

This should be `~/buildAPKs/var/cache/lib`

`find . -name "*build.gradle*" -exec grep implementation {} \; | grep -v \/\/ | grep -v fileTree\( | grep -v project\( | grep -v Class | grep -v Deps | grep -v \= | sort | uniq`

>Still trying to get it built though

Please review some of the older issues regarding `artifacts` and `libraries`.

**Comment by SDRausty** [comment]
>where I put them I just shortened it to make It easier to type

Thank you for clarifying.

**Comment by SDRausty** [comment]
>found (https://github.com/Lzhiyong/termux-ndk) and it manages to compile love2d! 

Great!
