### ISSUE TITLE
How can i debug my app?

### ISSUE THREAD

**Issue by rald** [BuildAPKs/buildAPKs#25]
my app compiles but just crash when run no error messages how can i debug it? and how can i see run time error messages? pls help me im just using a tablet no laptop or pc available

**Comment by SDRausty** [comment]
Can you please repeat your question at https://www.reddit.com/r/termux/ and cossreference it here when you do?  I would like to know the answer to your question too.

**Comment by SDRausty** [comment]
>app compiles but just crash when run no error messages 

Does it have all necessary permissions set to on?

**Comment by SDRausty** [comment]
[Can you please repeat your question at https://www.reddit.com/r/termux/ and cossreference it here when you do?  I would like to know the answer to your question too.](https://www.reddit.com/r/termux/comments/s72k6t/how_can_i_debug_my_app/)

**Comment by SDRausty** [comment]
> How can i debug my app?

>Catches a stack trace when an app crashes unexpectedly.

https://github.com/TacoTheDank/Scoop

**Comment by SDRausty** [comment]
>How can i debug my app?

Have you tried Settings > System > Developer options > Debugging/System Tracing in Android to debug your app?

**Comment by Anonymous2716** [comment]
If you don't have android 11 or higher  I don't think you can start ADB without an external device such as PC.
