### ISSUE TITLE
How add appcompat

### ISSUE THREAD

**Issue by yyyyyy-0976** [BuildAPKs/buildAPKs#28]
I add appcompat.arr and jar file in /data/data/com.termux/files/home/buildAPKs/var/cache/lib but it is still giving these 
Beginning build in ~/hello-jni/app/src/main/:
AndroidManifest.xml
BasePresenter.java
CMakeLists.txt
HelloJniActivity.java
HelloJniMvpView.java
HelloPresenter.java
MvpView.java
Presenter.java
User.java
activity_hello_jni.xml
app-utils.c
colors.xml
dimens.xml
dimens.xml
hello-jni.c
ic_launcher.png
ic_launcher.png
ic_launcher.png
ic_launcher.png
ic_launcher.png
strings.xml
styles.xml
Loading artifacts and libraries into the compilation:  Adding 2 artifacts and libraries from directory /data/data/com.termux/files/home/buildAPKs/var/cache/lib into build main :DONE
aapt: started...
res/values/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.

res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.

res/values/styles.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.

Signal generated aapt build.one.bash build.one.bash: EXITING...
buildAPKs signal 220 received by build.one.bash in /data/data/com.termux/files/home/hello-jni/app/src/main by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.main.log` file.

Running: VAR="$(grep -C 2 -ie error -ie errors "/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.main.log")" && VAR="$(grep -v \-\- <<< $VAR)" && head <<< $VAR && tail <<< $VAR
grep: /data/data/com.termux/files/home/buildAPKs/var/log/stnderr.main.log: No such file or directory
Completing tasks...
Completed tasks in ~/hello-jni/app/src/main/.

**Comment by SDRausty** [comment]
https://github.com/agnostic-apollo/agnostic-apollo/issues/1

**Comment by Anonymous2716** [comment]
This seems aapt issue.
