### ISSUE TITLE
Modifying `android.jar` Files on Device (building the aapt, ecj, dx and apksigner packages)

### ISSUE THREAD

**Issue by SDRausty** [BuildAPKs/buildAPKs#3]
Modifying `android.jar` might better than adding libraries. Hence this issue is devoted to rewriting the android.jar file.

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
android.jar is available at runtime in android os.

So modifications to it may lead problems.
Also it needs root and different versions of android uses different updated android.jar.

So it is not a good idea to modify it.

**Comment by SDRausty** [comment]
@HemanthJabalpuri do you know the steps to compile and decompile ` android.jar `?

> Also it needs root 

```
[09:15~]$ find $PREFIX/ -name android.jar -exec ls -og {} \;
-rw------- 1 3881775 Jul 22 14:39 /data/data/com.termux/files/usr/share/java/android.jar
-rw------- 1 3340986 Jun 19 14:14 /data/data/com.termux/files/usr/share/aapt/android.jar
```
Why do you state that root is needed?

**Comment by SDRausty** [comment]
@HemanthJabalpuri can you test https://github.com/BuildAPKs/buildAPKs.samples on device with https://github.com/sp4rkie/debian-on-termux please?

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
Sorry for late reply.

android.jar = /system/framework/framework.[apk & jar] + others too.

We are not compiling android.jar, i.e., we are only including it as classpath assuming that the target device have that in its bootclasspath.
All android devices bootclasspath has framework.jar for executing apps.

So if we want to modify android.jar, we also need to modify framework.jar in device too.

So modifying /system partition needs root.


Also https://github.com/BuildAPKs/buildAPKs.samples app compiled fine without Linux Distribution.

**Comment by SDRausty** [comment]
> including it as classpath

>> Unifying native artifacts should be a simple solution.  File [bootclasspath.sh](https://github.com/shlibs/shlibs.sh/blob/master/bootclasspath.sh) is created to ease inegrating of native libraries that are present on device.

Reference from https://github.com/BuildAPKs/buildAPKs/issues/2#issuecomment-560134368 

> assuming that the target device 

```
sed -i "s/minSdkVersion\=\"[0-9]\"/minSdkVersion\=\"$MSDKVERSION\"/g" AndroidManifest.xml 

sed -i "s/minSdkVersion\=\"[0-9][0-9]\"/minSdkVersion\=\"$MSDKVERSION\"/g" AndroidManifest.xml 

sed -i "s/targetSdkVersion\=\"[0-9]\"/targetSdkVersion\=\"$TSDKVERSION\"/g" AndroidManifest.xml 

sed -i "s/targetSdkVersion\=\"[0-9][0-9]\"/targetSdkVersion\=\"$TSDKVERSION\"/g" AndroidManifest.xml
```
[Reference from build.one.bash#L127&#L130)](https://github.com/BuildAPKs/buildAPKs/blob/master/scripts/bash/build/build.one.bash#L127&#L130)

**Comment by SDRausty** [comment]
> Also https://github.com/BuildAPKs/buildAPKs.samples app compiled fine without Linux Distribution.

@HemanthJabalpuri the reason this was requested:
> test https://github.com/BuildAPKs/buildAPKs.samples on device with https://github.com/sp4rkie/debian-on-termux please?

Are the errors important?  Oh yes, much so.  The [BuildAPKs modules/repositories and forks](https://github.com/BuildAPKs) are selected because they compile on device in Termux.  Can they compile in a [PRoot environment](https://termuxarch.github.io/docsTermuxArch/PRoot)?

>  compiled fine without Linux Distribution.

Studying the errors in [debian proot]( https://github.com/sp4rkie/debian-on-termux) has shed a little more light on this subject.  I would like to hear your opinion about the errors encountered.  

[BuildAPKs](https://github.com/BuildAPKs/buildAPKs/commits/master) was recently modified to run after one tap inside a debian proot environment.   The script sets up fine, and runs as it should except for the fact that compiling even a single APK is impossible id debian on device.  I would like to 👂 hear your opinion about the errors BuildAPKs shows in debian on device.

**Comment by SDRausty** [comment]
> bootclasspath has framework.jar for executing apps

grep -r colorPrimaryDark /system/framework/ 
Binary file /system/framework/framework-res.apk matches

**Comment by SDRausty** [comment]
> bootclasspath has framework.jar for executing apps


```
$ grep -r colorPrimaryDark /system/framework/
Binary file /system/framework/framework-res.apk matches
```

**Comment by SDRausty** [comment]
@HemanthJabalpuri you mentioned:

> All android devices bootclasspath has framework.jar for executing apps.

```
$ grep -r colorPrimary /system/framework/
Binary file /system/framework/framework-res.apk matches
```

Referencing [Parsing Project Configuration Files #1](https://github.com/BuildAPKs/buildAPKs/issues/1#issuecomment-534638948):
```
number of errors / type of error
4813 error: Error: No resource found that matches the given name: attr 'colorPrimary'.
```

It appears that you are absolutely correct:
```
$ mkdir tmp
$ cd tmp
$ unzip  /system/framework/framework-res.apk
.
.
.
$ grep -r colorPrimary .                                
Binary file ./resources.arsc matches
```

**Comment by SDRausty** [comment]
@HemanthJabalpuri you mentioned:

> All android devices bootclasspath has framework.jar for executing apps.

```
$ grep -r colorPrimary /system/framework/
Binary file /system/framework/framework-res.apk matches
```

Referencing [Parsing Project Configuration Files #1 issuecomment-534638948](https://github.com/BuildAPKs/buildAPKs/issues/1#issuecomment-534638948):
```
number of errors / type of error
4813 error: Error: No resource found that matches the given name: attr 'colorPrimary'.
```

It appears that you are absolutely correct:
```
$ mkdir tmp
$ cd tmp
$ unzip  -q /system/framework/framework-res.apk
$ grep -r colorPrimary .                                
Binary file ./resources.arsc matches
$ dpkg -S aapt 
.
aapt: /data/data/com.termux/files/usr/share/aapt/android.jar                                                    
.
$ cp /data/data/com.termux/files/usr/share/aapt/android.jar .
$ cp /system/framework/framework-res.apk /data/data/com.termux/files/usr/share/aapt/android.jar
```

**Comment by SDRausty** [comment]
```
grep colorPrimaryDark android.jar                 $ grep colorPrimaryDark /data/data/com.termux/files/usr/share/aapt/android.jar
colorPrimaryDark
```

```
$ ~/buildAPKs/build.github.bash google
.
.
.
Running: grep -iC 4 ERROR /data/data/com.termux/files/home/buildAPKs/var/log/stnderr.git.orgs.google.log | tail                                                 res/menu/menu_main.xml:4: error: No resource identifier found for attribute 'orderInCategory' in package 'android'
                                                                                res/values/styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

res/values/styles.xml:8: error: Error: No resource found that matches the given name: attr 'colorAccent'.                                                       
res/values/styles.xml:6: error: Error: No resource found that matches the given name: attr 'colorPrimary'.                                                                                                                                      res/values/styles.xml:7: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
```

**Comment by SDRausty** [comment]
> aapt doesn't add colorPrimaryDark to the build even though colorPrimaryDark is in android.jar

This commit https://github.com/BuildAPKs/buildAPKs/commit/e705a9a8b64b07c3d7fec5903acf90dce9a11021 resolves aapt doesn't add colorPrimaryDark.

**Comment by HemanthJabalpuri** [comment]
@SDRausty 
Since according to your output of grep, you can simply add framework-res.apk to aapt with -I flag of aapt.

**Comment by SDRausty** [comment]
@HemanthJabalpuri thank you for sharing; 
 This https://github.com/BuildAPKs/buildAPKs/commit/29f76de8ad9d6d4778cdd0b6547f4975897279b0 commit adds 
> framework-res.apk to aapt with -I flag 

The verbose output states ` Including resources from package: /system/framework/framework-res.apk `.  

However ` Error: No resource found that matches the given name: attr 'colorPrimaryDark'. ` and similar still persist after further testing.  

```
$ grep -r colorPrimaryDark /system 2>/dev/null | wc -l
76
$ grep colorPrimaryDark /system/framework/framework-res.apk 2>/dev/null | wc -l 
1
```

**Comment by SDRausty** [comment]
> add framework-res.apk to aapt with -I flag of aapt

Commit https://github.com/BuildAPKs/buildAPKs/commit/2fec19a288db2b8ed0f4679a7cc439cb2ea9d49e adds support for including many files with the -I flag to `aapt`. The result still appears to be unchanged and the error continues.

**Comment by SDRausty** [comment]
#### Notes about jar files used by BuildAPKs:

[# Create an android.jar with AndroidManifest.xml and resources.arsc:](https://github.com/termux/termux-packages/blob/master/packages/aapt/build.sh#L332)
  * https://github.com/termux/termux-packages/blob/master/packages/aapt/build.sh

[# Package classes.dex into jar:](https://github.com/termux/termux-packages/blob/master/packages/ecj/build.sh#L36)
  * https://github.com/termux/termux-packages/blob/master/packages/ecj/build.sh

[# Dex the rewritten jar file:](https://github.com/termux/termux-packages/blob/master/packages/dx/build.sh#L23)
  * https://github.com/termux/termux-packages/blob/master/packages/dx/build.sh

[jar cf apksigner.jar classes.dex ](https://github.com/termux/termux-packages/blob/master/packages/apksigner/build.sh#L25)
  * https://github.com/termux/termux-packages/blob/master/packages/apksigner/build.sh

How feasible is it to create these jar files on device with Termux?
